services:
  php:
    build:
      context: ./docker/php
    container_name: shop_php
    ports:
      - "8082:80"
    environment:
      DB_HOST: mariadb
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
      MAIL_SECRET_KEY: ${MAIL_SECRET_KEY}
      MAIL_SMTP_PASS: ${MAIL_SMTP_PASS}
      MAIL_SMTP_HOST: mailpit
      MAIL_SMTP_PORT: 1025
      APP_URL: http://localhost:8082
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./vendor:/var/www/html/vendor
      - ./.env:/var/www/html/.env
    depends_on:
      - mariadb
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: shop_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

  mariadb:
    image: mariadb:10.11
    container_name: shop_mariadb
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: shop_phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb

volumes:
  mariadb_data: